### ISSUE TITLE
Menu bar too crowded

### ISSUE THREAD

**Issue by TonyRippy** [TonyRippy/north-castle-veterans-site#32]
From @jskiera:
Can you stretch out the tabs a little bit? There are too many for its current size so it looks unorganized as of now.

**Comment by TonyRippy** [comment]
There's really no good way to fit them all in the menu bar, so I added a new "/cemeteries" page that serves as the list of all cemeteries. (Matches the pattern of the "/veterans" page.) I then modified the menu to include two fixed menu items, "Cemeteries" and "Veterans".

**Comment by jskiera** [comment]
I think this menu looks a lot more organized than before; I really like it!
Could you also add a tab labeled 'George Pouder' and center all of the
tabs? Thank you!
