### ISSUE TITLE
Problems saving Albert Ransom's page

### ISSUE THREAD

**Issue by TonyRippy** [TonyRippy/north-castle-veterans-site#33]
From @jskiera :
Ok, so there is a bug that I have run into while working on the site with the scouts. I mentioned it yesterday and it is that the saving Albert Ransom's page in St. Stephens cemetery section doesn't go through under a condition I discovered. There may be a word count limit of some sort because I have the revised bio in a separate doc which I shared with you and that bio won't save. However, when I tried to save a one word message, it saved.

**Comment by TonyRippy** [comment]
I think there are a couple of possibilities here. The first is that I notice the biography fields are being stored with a data type of 'STRING' instead of 'TEXT'. It could be that text fields allow you to store more data.

Another possibility is that the field is created as indexed. (Allows for faster lookups and sorted results.) According to the documentation:
https://cloud.google.com/datastore/docs/concepts/limits
An indexed field is limited to 1500 characters. 

I'm going to try changing the type, making sure it isn't indexed, and try saving it again will the full information.

**Comment by jskiera** [comment]
Ok it seems to have helped because I haven't run into any problems! Thanks!

**Comment by TonyRippy** [comment]
After digging into this further, it seems this is a bug in the Datastore API:
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1325

**Comment by TonyRippy** [comment]
There is a work-around mentioned in that bug, I'll use that for now.
