### ISSUE TITLE
Improved Cemetery page design 

### ISSUE THREAD

**Issue by TonyRippy** [TonyRippy/north-castle-veterans-site#34]
From @jskiera :
Also, I want to quickly go over that idea that I had for each cemetery page. I made an example of what I mean in that google slides doc we worked on before. I am wondering how is that coming along because I think that adding this type of mechanic would look rather interesting but if you've been having difficulty then it is not necessarily something I need to have on the site.

Link to doc:
https://docs.google.com/presentation/d/11YZEiaS7mNrlOHkiJSEm9ms90-TwCiyiEUJmDUdJeHE/edit#slide=id.g2523edac87_0_0

**Comment by TonyRippy** [comment]
Looks like this is pretty easy to do, once we have the image(s). You just need to pick a DIV to host the content (which we already have) and use the 'background' CSS attributes on that element:

HTML:
```html
<body>
  <div id="banner">
  <!-- The rest of your site's content -->
  </div>
</body>
```
CSS:
```css
#banner {
  background: url(banner.png) no-repeat center top; 
}
```

**Comment by jskiera** [comment]
I will have the pictures for each cemetery up asap. Where do I need to
change this code so I can do this? Or did u already set it up?

**Comment by jskiera** [comment]
Here are all the pictures! :
The one below is Archer Sarles






​

**Comment by jskiera** [comment]
Also could you help me alphabetize the names of the veterans by last name
please? Thank you!

**Comment by TonyRippy** [comment]
Hi Jack,

The images didn't seem to come through. Can you send them to me directly
via email?

- Tony

**Comment by jskiera** [comment]
Here you go!
​
 St. Stephens.PNG
<https://drive.google.com/file/d/0B3MX8aeb9w7_V3AzeDAxdU9ROGs/view?usp=drive_web>
​​
 Archer Sarles.PNG
<https://drive.google.com/file/d/0B3MX8aeb9w7_SzBrb0lGc2FqYVU/view?usp=drive_web>
​​
 The Old Fisher.png
<https://drive.google.com/file/d/0B3MX8aeb9w7_T0JUYXlHT29aRkk/view?usp=drive_web>
​​
 Methodist.PNG
<https://drive.google.com/file/d/0B3MX8aeb9w7_UUtYQUxRUFJsSGs/view?usp=drive_web>
​​
 Middle Patent.PNG
<https://drive.google.com/file/d/0B3MX8aeb9w7_X1pWa2JXQ29vUDQ/view?usp=drive_web>
​​
 The Old Quaker.png
<https://drive.google.com/file/d/0B3MX8aeb9w7_UVY4d1pXXzdaNVU/view?usp=drive_web>
​

**Comment by TonyRippy** [comment]
Hi Jack,

Thanks for the images, but unfortunately they are the wrong shape for the kind of design you were asking for. The images above are taller than they are wide, and fairly small. In order to do a banner image like in the presentation we need an image that is wide and short; around 940 pixels wide and 100-200 pixels high.

In the meantime I've added the images you provided to the cemetery pages, similar to how they're done on the veteran pages. Example: https://north-castle-veterans-site.appspot.com/cemetery/St_Stephens

**Comment by jskiera** [comment]
Ok! At this current time, I am very happy with how the cemetery pages look
now; the banner idea would be a little difficult to set up size wise. I
will send the other cemetery pictures when I have acquired them! Thank you!
