### ISSUE TITLE
Fill in list of scouts that helped enter data.

### ISSUE THREAD

**Issue by TonyRippy** [TonyRippy/north-castle-veterans-site#35]
We should give credit to volunteers that helped transcribe and edit the Veteran info.

Start here:
https://github.com/TonyRippy/north-castle-veterans-site/blob/master/src/main/webapp/thanks.jsp#L56

**Comment by jskiera** [comment]
I am giving credit to Mr Pouder as you can see in the site. Not sure if I
can with other volunteers because i haven't seen such a thing from other
eagle scout projects. But I want to give all of the them credit just need
to confirm if that is ok.

**Comment by TonyRippy** [comment]
Ok, in that case I'll remove the list. We can add it back later if you decide to mention the scouts by name.

**Comment by jskiera** [comment]
For volunteers like Scouts and adults, I'm not allowed to publicize their
names - only you and Mr. Pouder I believe!
